"""
Script:      hw02_eda.py
Purpose:     Exploratory Data Analysis (EDA) on Wildcat Capital's client
             transaction fact table.
Dataset:     data/raw/fact_transactions.csv
             (Wildcat Capital portfolio transactions, Jan 2020 - Dec 2024)
Author:      Hannah Dickinson
Generated:   2026-09-16 (generated by Claude Cowork from hw02/specification.md)
"""

import os
import itertools

import pandas as pd
import matplotlib.pyplot as plt

# Show full output without truncation
pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)
pd.set_option("display.width", 120)

# A running list of the lines that make up the plain-text profile
# (items 2-13 only, per the specification).
profile_lines = []


def log(message=""):
    """Print a line to the console AND capture it for the profile summary."""
    print(message)
    profile_lines.append(str(message))


def section(title):
    log("")
    log("=" * 70)
    log(title)
    log("=" * 70)


# ---------------------------------------------------------------------------
# 1. Load the data
# ---------------------------------------------------------------------------
df = pd.read_csv("data/raw/fact_transactions.csv")

# ---------------------------------------------------------------------------
# 2. Shape (rows x columns)
# ---------------------------------------------------------------------------
section("2. DATASET SHAPE")
log(f"Rows: {df.shape[0]:,}  |  Columns: {df.shape[1]}")

# ---------------------------------------------------------------------------
# 3. Column names and data types
# ---------------------------------------------------------------------------
section("3. COLUMN NAMES AND DATA TYPES")
log(df.dtypes.to_string())

# ---------------------------------------------------------------------------
# 4. Missing values per column
# ---------------------------------------------------------------------------
section("4. MISSING VALUES PER COLUMN")
log(df.isnull().sum().to_string())

# ---------------------------------------------------------------------------
# 5. Descriptive statistics for numeric columns
# ---------------------------------------------------------------------------
section("5. DESCRIPTIVE STATISTICS (NUMERIC COLUMNS)")
log(df.describe().to_string())

# ---------------------------------------------------------------------------
# 6. Value counts and percentages for txn_type (most to least frequent)
# ---------------------------------------------------------------------------
section("6. TXN_TYPE VALUE COUNTS AND PERCENTAGES")
txn_counts = df["txn_type"].value_counts()
txn_pcts = df["txn_type"].value_counts(normalize=True) * 100
txn_summary = pd.DataFrame({"count": txn_counts, "percent": txn_pcts.round(2)})
log(txn_summary.to_string())

# ---------------------------------------------------------------------------
# 7. Unique counts of clients, advisors, and securities
# ---------------------------------------------------------------------------
section("7. UNIQUE ENTITY COUNTS")
log(f"Unique clients:    {df['client_id'].nunique():,}")
log(f"Unique advisors:   {df['advisor_id'].nunique():,}")
log(f"Unique securities: {df['security_id'].nunique():,}")

# ---------------------------------------------------------------------------
# 8. Earliest and latest txn_date
# ---------------------------------------------------------------------------
section("8. TRANSACTION DATE RANGE")
txn_dates = pd.to_datetime(df["txn_date"])
log(f"Earliest txn_date: {txn_dates.min().date()}")
log(f"Latest txn_date:   {txn_dates.max().date()}")

# ---------------------------------------------------------------------------
# 9. Duplicate rows by txn_id
# ---------------------------------------------------------------------------
section("9. DUPLICATE TXN_ID CHECK")
duplicate_count = df["txn_id"].duplicated().sum()
log(f"Duplicate txn_id count: {duplicate_count:,}")

# ---------------------------------------------------------------------------
# 10. Mean, median, and skewness of amount
# ---------------------------------------------------------------------------
section("10. AMOUNT: MEAN, MEDIAN, SKEWNESS")
amount_mean = df["amount"].mean()
amount_median = df["amount"].median()
amount_skew = df["amount"].skew()
log(f"Mean amount:     {amount_mean:,.2f}")
log(f"Median amount:   {amount_median:,.2f}")
log(f"Skewness amount: {amount_skew:.2f}")

# ---------------------------------------------------------------------------
# 11. Group by txn_type: count, mean, median of amount (sorted by mean desc)
# ---------------------------------------------------------------------------
section("11. AMOUNT BY TXN_TYPE (GROUPED)")
grouped_amount = (
    df.groupby("txn_type")["amount"]
    .agg(count="count", mean="mean", median="median")
)
grouped_amount[["mean", "median"]] = grouped_amount[["mean", "median"]].round(2)
grouped_amount = grouped_amount.sort_values("mean", ascending=False)
log(grouped_amount.to_string())

# ---------------------------------------------------------------------------
# 12. Correlation matrix for shares, price, amount + top 3 correlations
# ---------------------------------------------------------------------------
section("12. CORRELATION MATRIX (shares, price, amount)")
corr_cols = ["shares", "price", "amount"]
corr_matrix = df[corr_cols].corr().round(2)
log(corr_matrix.to_string())

corr_pairs = []
for col_a, col_b in itertools.combinations(corr_cols, 2):
    corr_pairs.append((col_a, col_b, corr_matrix.loc[col_a, col_b]))
corr_pairs_sorted = sorted(corr_pairs, key=lambda pair: abs(pair[2]), reverse=True)

log("")
log("Three strongest correlations (excluding self-correlation):")
for rank, (col_a, col_b, value) in enumerate(corr_pairs_sorted[:3], start=1):
    log(f"  {rank}. {col_a} - {col_b}: {value:.2f}")

# ---------------------------------------------------------------------------
# 13. Negative shares check, broken out by txn_type
# ---------------------------------------------------------------------------
section("13. SHARES: MIN, MAX, NEGATIVE COUNT BY TXN_TYPE")
shares_by_type = df.groupby("txn_type")["shares"].agg(
    min_shares="min",
    max_shares="max",
    negative_count=lambda s: (s < 0).sum(),
)
log(shares_by_type.to_string())

# ---------------------------------------------------------------------------
# 14. Shape validation warning
# ---------------------------------------------------------------------------
expected_shape = (298772, 9)
if df.shape != expected_shape:
    print("")
    print("*" * 70)
    print(
        f"WARNING: Dataset shape {df.shape} does not match the expected "
        f"shape {expected_shape}. Investigate before proceeding with analysis."
    )
    print("*" * 70)

# ---------------------------------------------------------------------------
# 15. Charts: histogram, box plot, scatter plot
# ---------------------------------------------------------------------------
charts_dir = "charts"
os.makedirs(charts_dir, exist_ok=True)

# 15a. Histogram of amount with mean/median lines
plt.figure(figsize=(10, 6))
plt.hist(df["amount"].dropna(), bins=50, color="#4C72B0", edgecolor="white")
plt.axvline(amount_mean, color="red", linestyle="--", linewidth=2,
            label=f"Mean = {amount_mean:,.2f}")
plt.axvline(amount_median, color="green", linestyle="--", linewidth=2,
            label=f"Median = {amount_median:,.2f}")
plt.title("Distribution of Transaction Amount")
plt.xlabel("Amount")
plt.ylabel("Frequency")
plt.legend()
plt.tight_layout()
plt.savefig(os.path.join(charts_dir, "hist_amount.png"), dpi=150)
plt.close()

# 15b. Horizontal box plot of amount by txn_type
plt.figure(figsize=(10, 6))
txn_types_ordered = grouped_amount.index.tolist()
box_data = [df.loc[df["txn_type"] == t, "amount"].dropna() for t in txn_types_ordered]
try:
    # matplotlib >= 3.9 renamed this argument
    plt.boxplot(box_data, tick_labels=txn_types_ordered, vert=False)
except TypeError:
    plt.boxplot(box_data, labels=txn_types_ordered, vert=False)
plt.title("Transaction Amount by Type")
plt.xlabel("Amount")
plt.ylabel("Transaction Type")
plt.tight_layout()
plt.savefig(os.path.join(charts_dir, "box_amount_by_type.png"), dpi=150)
plt.close()

# 15c. Scatter plot of shares vs. amount, colored by txn_type
plt.figure(figsize=(10, 6))
for txn_type in df["txn_type"].unique():
    subset = df[df["txn_type"] == txn_type]
    plt.scatter(subset["shares"], subset["amount"], s=8, alpha=0.5, label=txn_type)
plt.title("Shares vs. Amount by Transaction Type")
plt.xlabel("Shares")
plt.ylabel("Amount")
plt.legend(markerscale=2, title="txn_type")
plt.tight_layout()
plt.savefig(os.path.join(charts_dir, "scatter_shares_amount.png"), dpi=150)
plt.close()

print("")
print(f"Charts saved to '{charts_dir}/':")
print("  - hist_amount.png")
print("  - box_amount_by_type.png")
print("  - scatter_shares_amount.png")

# ---------------------------------------------------------------------------
# 16. Save plain-text summary of items 2-13
# ---------------------------------------------------------------------------
profile_path = "hw02_profile.txt"
profile_dir = os.path.dirname(profile_path)
if profile_dir:
    os.makedirs(profile_dir, exist_ok=True)
with open(profile_path, "w") as f:
    f.write("\n".join(profile_lines))
    f.write("\n")

print("")
print(f"Profile summary saved to '{profile_path}'")
